---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: catalogue-2
  name: catalogue-2
  namespace: sock-shop-nr
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: catalogue-2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: catalogue-2
    spec:
      containers:
      - env:
        - name: NEW_RELIC_APP_NAME
          value: k8s_catalogue-2
        - name: NEW_RELIC_LICENSE_KEY
          value: 4a91dbcc8d10a3ca560b9713ba3f21e72732NRAL
        - name: NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
          value: "true"
        - name: NEW_RELIC_DISABLE_VM_SAMPLER
          value: "true"
        - name: NEW_RELIC_INFINITE_TRACING_TRACE_OBSERVER_HOST
          value: 04f23304-ae8f-4232-b884-a51dc9a41baf.aws-ap-southeast-1.tracing.edge.nr-data.net
        - name: DB_HOST
          value: catalogue-db-2
        - name: RAILS_LOG_TO_STDOUT
          value: "true"
        - name: RAILS_MAX_THREADS
          value: "20"
        image: azumax/catalogue-2:test
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 300
        name: catalogue
        ports:
        - containerPort: 3000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 300
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 2Gi
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - all
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        beta.kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
